name: riftbound
logger:
  level: INFO
socket:
  server_key: riftbound-debug-key
session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 604800
console:
  username: admin
  password: riftbound-debug-console
runtime:
  path: /nakama/data/modules
  http_key: riftbound-debug-http

matchmaker:
  interval_sec: 1
  max_intervals: 8
